In [ ]:
pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 2.1 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [ ]:
import pymysql

In [23]:
con=pymysql.connect(host="mysql-gaurav-hirulkargaurav348-6e84.h.aivencloud.com",port=26168,user="avnadmin",password="AVNS_liKX8-67OO77oJC7wH4",database="project1db");

print("Data base is connected Successfully")

Data base is connected Successfully

In [20]:
curs=con.cursor()

In [ ]:
name=input("Enter the name of student :")
curs.execute(f" select student_name, student_clgnm from students where student_name='{name}'");
data=curs.fetchone()
print(data)

Enter the name of student :Gaurav
('Gaurav', 'Sipna')

In [32]:
ID=int(input("Enter the ID of student :"))
name=input("Enter the name of student :")
clf=input("Enter the college name :")
mobile=input('Enter the mobile number :')
course=input("Enter the course : ")
curs=con.cursor()
curs.execute(f" insert into students values({ID},'{name}','{clf}','{mobile}','{course}')")
con.commit()
print("Data is inserted Successfully")

Enter the ID of student :126
Enter the name of student :soham
Enter the college name :sipna
Enter the mobile number :146186448
Enter the course : Ml
Data is inserted Successfully